//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libreria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public string idVenta { get; set; }
        public int monto { get; set; }
        public System.DateTime fecha { get; set; }
        public int fkLibro { get; set; }
        public int fkCliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual libro libro { get; set; }
    }
}
