//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingsOnFire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class anillo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public anillo()
        {
            this.encargo = new HashSet<encargo>();
        }
    
        public int idAnillo { get; set; }
        public string material { get; set; }
        public int circunferencia { get; set; }
        public Nullable<int> peso { get; set; }
        public int precio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<encargo> encargo { get; set; }
    }
}
