//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RingsOnFire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class encargo
    {
        public int idEncargo { get; set; }
        public System.DateTime fechaEncargo { get; set; }
        public System.DateTime fechaEntrega { get; set; }
        public int monto { get; set; }
        public int fkCliente { get; set; }
        public int fkAnillo { get; set; }
    
        public virtual anillo anillo { get; set; }
        public virtual cliente cliente { get; set; }
    }
}
