//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Silla
    {
        public int fila { get; set; }
        public int noSilla { get; set; }
        public string tipo { get; set; }
        public string estado { get; set; }
        public int cantidad { get; set; }
        public string idSilla { get; set; }
        public int fkNoSala { get; set; }
        public string fkIdReserva { get; set; }
    
        public virtual reserva reserva { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
